MFT_Explorer/MFT/MFTEXP/MFTEXP/Controllers/MFTController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

using MFTEXP.Classes;
using MFTEXP.Models;

using System.Text;
using System.Web.Script.Serialization;

namespace MFTEXP.Controllers
{
    public class MFTController : Controller
    {
        //
        // GET: /MFT/

        public ActionResult Index()
        {
            return View();
        }

        #region AGENTS
        public ActionResult Agents()
        {
            return View("~/Views/MFT/MFTAgent.cshtml");
        }

        public JsonResult GetAgents()
        {
            var response = new JsonRespnse();
            try
            {
                MFTAgent Agt = new MFTAgent();
                response.Result = new AgentsJsonResult() {
                    Agents = Agt.GetAgents()
                };
                response.Status = JsonResponseStatus.Success;
            }
            catch (Exception ex)
            {
                response.Status = JsonResponseStatus.Failure ;
                response.Error = new JsonResponseError() { Message = MFTConstants.Request_Failure_Message };
            }
            return Json(response, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region MONITORS
        public ActionResult Monitors()
        {
            return View("~/Views/MFT/MFTMonitor.cshtml");
        }

        public JsonResult GetMonitors()
        {
            var response = new JsonRespnse();
            try
            {
                MFTMonitor mntr = new MFTMonitor();
                response.Result = new MonitorsJsonResult()
                {
                    Monitors = mntr.GetMonitors()
                };
                response.Status = JsonResponseStatus.Success;
            }
            catch (Exception ex)
            {
                response.Status = JsonResponseStatus.Failure;
                response.Error = new JsonResponseError() { Message = MFTConstants.Request_Failure_Message };
            }
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        public JsonResult PerformMonitorAction(string QMGR, string MID, string MName, string AName, MFTCommon.Current_Action_Performed actiontype)
        {
            var response = new JsonRespnse();
            try
            {
                MFTMonitor mnclass = new MFTMonitor();
                if (!mnclass.Perform_Monitor_Action(MID, MName, QMGR, AName, actiontype))
                {
                    response.Status = JsonResponseStatus.Failure;
                    response.Error = new JsonResponseError() { Message = MFTConstants.Request_Failure_Message };
                }
                else
                {
                    response.Status = JsonResponseStatus.Success;
                }
                MFTMonitor mntr = new MFTMonitor();
                response.Result = new MonitorsJsonResult()
                {
                    Monitors = mntr.GetMonitors()
                };
            }
            catch (Exception ex)
            {
                response.Status = JsonResponseStatus.Failure;
                response.Error = new JsonResponseError() { Message = MFTConstants.Request_Failure_Message };
            }
           return Json(response, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region QUEUES
        public ActionResult Queues()
        {
            return View("~/Views/MFT/MFTQueue.cshtml");
        }

        public JsonResult GetAllQueues(String Prefix, string QMgr)
        {
            var response = new JsonRespnse();
            try
            {
                JavaScriptSerializer jsonObj = new JavaScriptSerializer();
                MQ_QueueeManager qMgr = jsonObj.Deserialize<MQ_QueueeManager>(QMgr);

                MFTQueue Que = new MFTQueue();
                response.Result = new QueuesJsonResult() {
                    Queues  = Que.GetAllQueues(Prefix, qMgr)
                };
                response.Status = JsonResponseStatus.Success;
            }
            catch (Exception ex)
            {
                response.Status = JsonResponseStatus.Failure;
                response.Error = new JsonResponseError() { Message = MFTConstants.Request_Failure_Message };
            }
            return Json(response, JsonRequestBehavior.AllowGet);                        
        }
        #endregion

        #region TRANSFERS / MONITORS
        public ActionResult Transfers()
        {
            return View("~/Views/MFT/MFTMonitorCreation.cshtml");
        }

        public JsonResult GetAgents_QMgrs()
        {
            var response = new JsonRespnse();
            try
            {
                MFTCommon mftcommon = new MFTCommon();
                MFTQueueManager mftManager = new MFTQueueManager();
                response.Result = new AgentsManagersJsonResult()
                {
                    Agents = mftcommon.GetAgentsandQMGR(),
                    Managers =  mftManager.GetAllQueueManagers()
                };
                response.Status = JsonResponseStatus.Success;
            }
            catch (Exception ex)
            {
                response.Status = JsonResponseStatus.Failure;
                response.Error = new JsonResponseError() { Message = MFTConstants.Request_Failure_Message };
            }
            return Json(response, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetQueues(string QMgr, string environment)
        {
            var response = new JsonRespnse();
            try
            {
                //JavaScriptSerializer jsonObj = new JavaScriptSerializer();
                //MQ_QueueeManager qMgr = jsonObj.Deserialize<MQ_QueueeManager>(QMgr);

                MFTMonitorCreation MFTTrans = new MFTMonitorCreation();
                response.Result = new QueuesJsonResult()
                {
                    Queues = MFTTrans.GetAllQueueNames(QMgr, environment)
                };
                response.Status = JsonResponseStatus.Success;
            }
            catch (Exception ex)
            {
                response.Status = JsonResponseStatus.Failure;
                response.Error = new JsonResponseError() { Message = MFTConstants.Request_Failure_Message };
            }
            return Json(response, JsonRequestBehavior.AllowGet);                        
        }
                
        public JsonResult BuildMonitor(string requestMonitor)
        {
            var response = new JsonRespnse();
            try
            {
                JavaScriptSerializer jsonObj = new JavaScriptSerializer();
                Transfer_details data = jsonObj.Deserialize<Transfer_details>(requestMonitor);

                MFTMonitorCreation MFTTrans = new MFTMonitorCreation();
                Boolean ActionComplete = false;
                if (!string.IsNullOrEmpty(data.Action))
                {
                    if (data.Action.Trim() == "Create")
                    {
                        ActionComplete = MFTTrans.CreateXML(data, MFTCommon.RequestType.Monitor);

                    }
                    else if (data.Action.Trim() == "Edit")
                    {
                        MFTMonitor mcls = new MFTMonitor();
                        Boolean monitordeleted = mcls.PutMessage(data.Monitor_ID.Trim(), data.Monitor_Name.Trim().ToUpper(), data.Exists_QueMGR.Trim(), data.Exists_AgentName.Trim(), MFTCommon.Current_Action_Performed.Deleted);
                        if (monitordeleted)
                        {
                            MFTMonitor monitor = new MFTMonitor();
                            monitor.InsertDeletedMonitorNames(data.Monitor_ID);
                            ActionComplete = MFTTrans.CreateXML(data, MFTCommon.RequestType.Monitor);
                        }
                    }
                    else
                    {
                        ActionComplete = MFTTrans.CreateXML(data, MFTCommon.RequestType.Onetimetransfer);
                    }

                    if (!ActionComplete)
                    {
                        response.Status = JsonResponseStatus.Failure;
                        response.Error = new JsonResponseError() { Message = MFTConstants.Request_Failure_Message };
                    }
                    else
                    {
                        response.Status = JsonResponseStatus.Success;
                    }
                }


                MFTMonitor mntr = new MFTMonitor();
                response.Result = new MonitorsJsonResult()
                {
                    Monitors = mntr.GetMonitors()
                };
            }
            catch (Exception ex)
            {
                response.Status = JsonResponseStatus.Failure;
                response.Error = new JsonResponseError() { Message = MFTConstants.Request_Failure_Message };
            }
            return Json(response, JsonRequestBehavior.AllowGet);
       }

        public JsonResult GetMonitordetails(string MonitorID)
        {
            var response = new JsonRespnse();
            try
            {
                MFTMonitorCreation MFTTrans = new MFTMonitorCreation();
                response.Result = new TransferDetailsJsonResult()
                {
                    MonitorDetails = MFTTrans.GetMonitorValues(MonitorID)
                };
                response.Status = JsonResponseStatus.Success;
            }
            catch (Exception ex)
            {
                response.Status = JsonResponseStatus.Failure;
                response.Error = new JsonResponseError() { Message = MFTConstants.Request_Failure_Message };
            }
            return Json(response, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region SCHEDULES
        public ActionResult Schedules()
        {
            return View("~/Views/MFT/MFTScheduler.cshtml");
        }

        public JsonResult GetScheduledTransfers()

MFT_Explorer/MFT/MFTEXP/MFTEXP/Views/MFT/MFTHostConfig.cshtml
@{
    ViewBag.Title = "MFTHostConfig";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<h2> Host Configuration</h2>
<script type="text/javascript" src="@Url.Content("~/Scripts/Custom/MFT/MFTHostConfig.js")"></script>
<div id="angular_Container" data-ng-app="HOSTCFG">
    <div data-ng-controller="HostController as hostcfg" data-ng-init="hostcfg.GetHosts()">
       <div class="container-fluid">
         <div data-ng-show="hostcfg.showtable">
                <button class="btn btn-primary col-md-offset-10" 
                        data-ng-show="hostcfg.resultsObj.totalItems<1"
                        data-ng-click="hostcfg.CallAdd()">
                    <span class="glyphicon glyphicon-plus-sign"> New Host
                </span>
                </button>
            </div>
            <div class="col-md-4" data-ng-show="hostcfg.showadd">
                <br />
                <span class="label label-primary">Host Name</span>
                <input class="form-control" type="text" data-ng-model="hostcfg.Host.Host_Name" />
                <span class="label label-primary">Host IP</span>
                <input class="form-control" type="text" data-ng-model="hostcfg.Host.Host_IP" />
                <span class="label label-primary">Coordination QMGR</span>
                <input class="form-control" type="text" data-ng-model="hostcfg.Host.Coord_Qmgr" />
                <span class="label label-primary">Coordination QMGR Port</span>
                <input class="form-control" type="number" data-ng-model="hostcfg.Host.Coord_Port" />
                <span class="label label-primary">Agent QMGR</span>
                <input class="form-control" type="text" data-ng-model="hostcfg.Host.Agent_QMGR" />
                <span class="label label-primary">Agent QMGR Port</span>
                <input class="form-control" type="number" data-ng-model="hostcfg.Host.Agent_QMGR_Port" />
                <span class="label label-primary">Default Channel</span>
                <input class="form-control" type="text" data-ng-model="hostcfg.Host.Default_Channel" />
                <span class="label label-primary">User ID</span>
                <input class="form-control" type="text" data-ng-model="hostcfg.Host.Userid" />
                <span class="label label-primary">Active</span>
                <input class="form-control" type="checkbox" data-ng-model="hostcfg.Host.active" data-ng-checked="hostcfg.Host.active=='Y'" data-ng-true-value="'Y'" data-ng-false-value="'N'" />
                <br />
                <button type="button" class="btn btn-primary btn-sm" data-ng-click="hostcfg.PerformAddorUpdate()">
                                <span class="glyphicon glyphicon-save"></span>&nbsp;{{hostcfg.savebuttonlabel}}
                            </button>
                            <span class="text-danger">&nbsp;</span>
                            <button type="button" class="btn btn-primary btn-sm" data-ng-click="hostcfg.Cancel()">
                                <span class="glyphicon glyphicon-unchecked"></span>&nbsp;Cancel
                            </button>
            
              </div>
            <br />
            <div class="panel panel-primary" data-ng-show="hostcfg.showtable">
                <div class="panel-heading">
                    <pagination total-items="hostcfg.resultsObj.totalItems"
                                data-ng-model="hostcfg.resultsObj.currentPage"
                                items-per-page="hostcfg.resultsObj.pageSize"
                                max-size="hostcfg.resultsObj.numPages"
                                boundary-links="true"
                                class="pull-left pagination-sm"
                                data-ng-change="hostcfg.resultsObj.pageChanged()">
                    </pagination>
                    &nbsp;&nbsp;
                    <span class="Grid_Panel_header">Displaying {{hostcfg.resultsObj.startRecord}} through {{hostcfg.resultsObj.endRecord}} out of {{hostcfg.resultsObj.totalItems}}</span>
                    <button type="button" class="btn btn-default btn-sm" title="Results Per Page">
                        <span class="dropdown" dropdown>
                            <a href="" class="dropdown-toggle" dropdown-toggle>
                                <span class="caret"></span>
                                {{hostcfg.resultsObj.pageSize}} Results Per Page
                            </a>
                            <ul class="dropdown-menu">
                                <li data-ng-repeat="result in hostcfg.resultsObj.availPageSizes">
                                    <a href="" data-ng-click="hostcfg.resultsObj.setPageSize(result)">{{result}}</a>
                                </li>
                            </ul>
                        </span>
                    </button>
                </div>
                <div class="panel-body">
                    <div class="panel panel-default">
                        <table class="table table-striped">
                            <thead>
                                <tr>
                                    <th data-ng-show="false">id</th>
                                    <th>Host Name</th>
                                    <th>Host IP</th>
                                    <th>Coordination QMGR</th>
                                    <th>Coordination QMGR Port</th>
                                    <th>Agent QMGR</th>
                                    <th>Agent QMGR Port</th>
                                    <th>Default Channel</th>
                                    <th>User ID</th>
                                    <th>Active</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tr data-ng-repeat="item in hostcfg.resultsObj.currentResults.details">
                                <td data-ng-show="false">{{item.Host_ID}}</td>
                                <td>{{ item.Host_Name }}</td>
                                <td>{{ item.Host_IP }}</td>
                                <td>{{ item.Coord_Qmgr }}</td>
                                <td>{{ item.Coord_Port }}</td>
                                <td>{{ item.Agent_QMGR }}</td>
                                <td>{{ item.Agent_QMGR_Port }}</td>
                                <td>{{ item.Default_Channel }}</td>
                                <td>{{ item.Userid }}</td>
                                <td>{{item.Active}}</td>
                                <td class="col-md-1">
                                    <button class="btn btn-primary" data-ng-click="hostcfg.PerformEditAction(item)">
                                        <span class="glyphicon glyphicon-pencil"></span>
                                    </button>
                                   <button class="btn btn-danger" data-ng-click="hostcfg.DeleteDialog(item)">
                                        <span class="glyphicon glyphicon-remove"></span>
                                    </button>
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script type="text/ng-template" id="HostDialog.html">
        <div class="modal-header label-info">
            <h2 class="modal-title label label-info">{{ dlgCtrl.heading }}</h2>
        </div>
        <div>
            <pre>{{dlgCtrl.details}}</pre>
        </div>
        <div class="modal-footer">
            <button class="btn btn-primary" data-ng-click="dlgCtrl.Close()">OK</button>
        </div>
    </script>
    <script type="text/ng-template" id="DeleteDialog.html">
        <div class="modal-header label-info">
            <h2 class="modal-title label label-info">Please Confirm ...</h2>
        </div>
        <div>
            <pre>{{dlgCtrl.heading}}</pre>
        </div>
        <div class="modal-footer">
    <button class="btn btn-success" data-ng-click="dlgCtrl.Yes()">Yes</button>
            <button class="btn btn-warning" data-ng-click="dlgCtrl.Close()">No</button>
        </div>
    </script>   


</div>

MFT_Explorer/MFT/MFTEXP/MFTEXP/Views/MFT/MFTMonitor.cshtml
@{
    ViewBag.Title = "MFTMonitor";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Monitors</h2>
<script type="text/javascript" src="@Url.Content("~/Scripts/Custom/MFT/MFTMonitor.js")"></script>

<div id="angular_Monitor" data-ng-app="Monitors">
    <div data-ng-controller="MonitorController as Mntr" data-ng-init="Mntr.GetMonitors()">
        <div class="container-fluid">
            <div>
                <div data-ng-show="'true'">
                    <a href="@Url.Action("Transfers", "MFT")" class="btn btn-primary col-md-offset-10"><span class="glyphicon glyphicon-plus-sign"> New Monitor</span></a>
                </div>
            </div>
            <br />
            </div>
            <div class="panel panel-primary">
                <div class="panel-heading">
                    <pagination total-items="Mntr.resultsObj.totalItems"
                                data-ng-model="Mntr.resultsObj.currentPage"
                                items-per-page="Mntr.resultsObj.pageSize"
                                max-size="Mntr.resultsObj.numPages"
                                boundary-links="true"
                                class="pull-left pagination-sm"
                                data-ng-change="Mntr.resultsObj.pageChanged()">
                    </pagination>
                    &nbsp;&nbsp;
                    <span class="Grid_Panel_header">Displaying {{Mntr.resultsObj.startRecord}} through {{Mntr.resultsObj.endRecord}} out of {{Mntr.resultsObj.totalItems}}</span>
                    <button type="button" class="btn btn-default btn-sm" title="Results Per Page">
                        <span class="dropdown" dropdown>
                            <a href class="dropdown-toggle" dropdown-toggle>
                                <span class="caret"></span>
                                {{Mntr.resultsObj.pageSize}} Results Per Page
                            </a>
                            <ul class="dropdown-menu">
                                <li data-ng-repeat="result in Mntr.resultsObj.availPageSizes">
                                    <a href data-ng-click="Mntr.resultsObj.setPageSize(result)">{{result}}</a>
                                </li>
                            </ul>
                        </span>
                    </button>
                    <div class="pull-right col-md-3">
                        <div class="col-xs-9">
                            <div class="right-inner-addon">
                                <label class="btn btn-info btn-sm" data-ng-show="Mntr.HideStatus!=' '"  data-ng-model="Mntr.HideStatus"  btn-radio="' '">Show All Monitors</label>
                                <label class="btn btn-info  btn-sm" data-ng-show="Mntr.HideStatus==' '"  data-ng-model="Mntr.HideStatus"  btn-radio="'Stopped'">Show Active Monitors</label>
                                @*Show All Monitors <input  type="checkbox" data-ng-model="Mntr.HideStatus" 
                                     data-ng-checked="Mntr.HideStatus==' '" 
                                    data-ng-true-value="' '" data-ng-false-value="'Stopped'" />*@
                                @*<input type="search"
                                       class="form-control"
                                       placeholder="Search" data-ng-model="Mntr.search" />*@
                            </div>
                        </div>
                        <div class="pull-right btn-group btn-group-sm">
                            <button class="btn btn-primary" data-ng-click="Mntr.RefreshMonitor()" data-toggle="Refresh" title="Refresh">
                                <span class="glyphicon glyphicon-refresh"></span>
                            </button>
                        </div>
                    </div>
                </div>
                <div class="panel-body">
                    <div class="panel panel-default">
                        <table class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>
                                        <a href="#" data-ng-click="Mntr.sortType = 'MonitorName';Mntr.sortReverse=!Mntr.sortReverse">
                                            Monitor Name
                                            <span data-ng-show="Mntr.sortType == 'MonitorName'" data-ng-class="{'fa':true,'fa-caret-down':!Mntr.sortReverse,'fa-caret-up':Mntr.sortReverse}"></span>
                                        </a>
                                    </th>
                                    <th>
                                        <a href="#" data-ng-click="Mntr.sortType = 'QueueManagerName';Mntr.sortReverse=!Mntr.sortReverse">
                                            Queue Manager Name
                                            <span data-ng-show="Mntr.sortType == 'QueueManagerName'" data-ng-class="{'fa':true,'fa-caret-down':!Mntr.sortReverse,'fa-caret-up':Mntr.sortReverse}"></span>
                                        </a>
                                    </th>
                                    <th>
                                        <a href="#" data-ng-click="Mntr.sortType = 'AgentName';Mntr.sortReverse=!Mntr.sortReverse">
                                            Agent
                                            <span data-ng-show="Mntr.sortType == 'AgentName'" data-ng-class="{'fa':true,'fa-caret-down':!Mntr.sortReverse,'fa-caret-up':Mntr.sortReverse}"></span>
                                        </a>
                                    </th>
                                    <th>
                                        <a href="#" data-ng-click="Mntr.sortType = 'MonitorStatus';Mntr.sortReverse=!Mntr.sortReverse">
                                            Status
                                            <span data-ng-show="Mntr.sortType == 'MonitorStatus'" data-ng-class="{'fa':true,'fa-caret-down':!Mntr.sortReverse,'fa-caret-up':Mntr.sortReverse}"></span>
                                        </a>
                                    </th>
                                    <th  >
                                        XML
                                    </th>
                                    <th  class="col-md-2" >
                                        Action
                                    </th>
                                </tr>
                            </thead>
                            <tr data-ng-repeat="item in Mntr.resultsObj.currentResults.details | orderBy:Mntr.sortType:Mntr.sortReverse |filter: {MonitorStatus: '!' + Mntr.HideStatus} ">
                                <td>{{ item.MonitorName }}</td>
                                <td>{{ item.QueueManagerName }}</td>
                                <td>{{ item.AgentName + "[ " + item.AgentStatus + " ]" }}</td>
                                <td>{{ item.MonitorStatus }}</td>
                                <td>
                                    <button class="btn btn-info" data-ng-click="Mntr.XmlDialog(item)" data-toggle="tooltip" title="Show XML">
                                        <span class="glyphicon glyphicon-eye-open"></span>
                                    </button>
                                </td>
                                <td class="col-md-2" data-ng-show="item.AgentStatus== 'STARTED' ||  item.AgentStatus== 'READY'  ">                                    
                                    
                                    <button class="btn btn-success" data-ng-hide="item.MonitorStatus =='Running' || item.MonitorStatus =='Stopped'" data-ng-click="Mntr.PerformAction(item,'started')" data-toggle="tooltip" title="Start">
                                        <span class="glyphicon glyphicon-play-circle"></span>
                                    </button>
                                    <button class="btn btn-warning" data-ng-hide="item.MonitorStatus =='Paused' || item.MonitorStatus =='Stopped'" data-ng-click="Mntr.PerformAction(item,'paused')" data-toggle="tooltip" title="Pause">
                                        <span class="glyphicon glyphicon-pause"></span>
                                    </button>
                                    <button class="btn btn-danger" data-ng-show="item.MonitorStatus =='Paused' || item.MonitorStatus =='Stopped'" data-ng-click="Mntr.DeleteDialog(item)" data-toggle="tooltip" title="Delete">
                                        <span class="glyphicon glyphicon-remove-sign"></span>
                                    </button>
                                </td>
                            </tr>
                        </table>
                    </div>
                </div>
            </div>
        </div>


        
    <script type="text/ng-template" id="MonitorDialog.html">
        <div class="modal-header label-info">
            <h2 class="modal-title label label-info">{{ dlgCtrl.heading }}</h2>
        </div>
        <div>
            <pre>{{dlgCtrl.details}}</pre>
        </div>
        <div class="modal-footer">
            <button class="btn btn-primary" data-ng-click="dlgCtrl.Close()">OK</button>
        </div>
    </script>

    <script type="text/ng-template" id="DeleteDialog.html">
        <div class="modal-header label-info">
            <h2 class="modal-title label label-info">Please Confirm ...</h2>
        </div>
        <div>
            <pre>{{dlgCtrl.heading}}</pre>
        </div>
        <div class="modal-footer">
    <button class="btn btn-success" data-ng-click="dlgCtrl.Yes()">Yes</button>
            <button class="btn btn-warning" data-ng-click="dlgCtrl.Close()">No</button>
        </div>
    </script>


    <script type="text/ng-template" id="XmlDialog.html">
        <div class="modal-header label-info">
            <h2 class="modal-title label label-info">{{ dlgCtrl.heading }}</h2>
        </div>
        <div class="modal-body">
            <div style="padding:20px; width:850px; max-height: 400px; overflow:auto; text-wrap:wrap-word;">        
                <pre>{{dlgCtrl.details}}</pre>
            </div>
        </div>
        <div class="modal-footer">
            <button class="btn btn-primary" data-ng-click="dlgCtrl.Close()">OK</button>
        </div>
    </script>
</div>